# Generated by Django 2.2.4 on 2019-09-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tmp_key', models.CharField(blank=True, max_length=200)),
                ('token', models.CharField(blank=True, max_length=200, unique=True)),
                ('ctr', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('email_hash', models.CharField(max_length=400, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('IV', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('active_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caronte_server.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronte_server.User'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=200)),
                ('key_iv', models.CharField(max_length=200)),
                ('ticket_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caronte_server.Ticket')),
                ('ticket_B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_ticket', to='caronte_server.Ticket')),
            ],
        ),
    ]
