# Generated by Django 2.1.7 on 2019-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField()),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
