# Generated by Django 2.1.7 on 2019-04-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('key_A', models.CharField(max_length=200)),
                ('key_B', models.CharField(max_length=200)),
                ('key_iv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('IV', models.CharField(blank=True, max_length=100, null=True)),
                ('ctr', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
                ('user_data', models.CharField(blank=True, max_length=200)),
                ('sys_data', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('email_hash', models.CharField(max_length=400, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('IV', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('pw_score', models.IntegerField(default=0)),
                ('active_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caronte_server.Token')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronte_server.User'),
        ),
        migrations.AddField(
            model_name='session',
            name='token_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caronte_server.Token'),
        ),
        migrations.AddField(
            model_name='session',
            name='token_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_token', to='caronte_server.Token'),
        ),
        migrations.AddField(
            model_name='session',
            name='user_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caronte_server.User'),
        ),
        migrations.AddField(
            model_name='session',
            name='user_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_user', to='caronte_server.User'),
        ),
    ]
