# Generated by Django 2.1.7 on 2019-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IV',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
