# Generated by Django 2.1.7 on 2019-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0004_user_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.IntegerField(default=2),
        ),
    ]
