# Generated by Django 2.1.7 on 2019-04-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0006_auto_20190327_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('random', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('IV', models.CharField(blank=True, max_length=100, null=True)),
                ('ctr', models.IntegerField(default=0)),
                ('user_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronte_server.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caronte_server.Token'),
        ),
    ]
