# Generated by Django 2.1.7 on 2019-04-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0007_auto_20190401_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='random',
        ),
        migrations.RemoveField(
            model_name='token',
            name='salt',
        ),
        migrations.AddField(
            model_name='token',
            name='sys_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='token',
            name='user_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
