# Generated by Django 2.1.7 on 2019-04-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0008_auto_20190401_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='sys_token',
            new_name='sys_data',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='user_token',
            new_name='user_data',
        ),
    ]
