# Generated by Django 2.1.7 on 2019-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0009_auto_20190401_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
