# Generated by Django 2.1.7 on 2019-04-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0010_token_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
