# Generated by Django 2.1.7 on 2019-04-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0011_token_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='active',
        ),
    ]
