# Generated by Django 2.1.7 on 2019-04-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caronte_server', '0012_remove_token_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_type',
        ),
    ]
